// frontend/src/components/JobHistoryPanel.jsx
import { useEffect, useState } from "react";
import { api } from "../api/client";
import { useFocusTrap } from "../hooks/useFocusTrap";
import { gitLabCommitUrl } from "../utils/gitlab";

export function JobHistoryPanel({ repository, onClose }) {
  const trapRef = useFocusTrap();
  const [jobs, setJobs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [freshness, setFreshness] = useState(null);
  const [checking, setChecking] = useState(false);

  useEffect(() => {
    api.listRepositoryJobs(repository.id)
      .then(setJobs)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, [repository.id]);

  const checkFreshness = async () => {
    setChecking(true); setError("");
    try { setFreshness(await api.checkRepositoryStaleness(repository.id)); }
    catch (err) { setError(err.message); }
    finally { setChecking(false); }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <section ref={trapRef} className="history-panel" role="dialog" aria-modal="true" aria-label="Historial de indexado" onClick={(e) => e.stopPropagation()}>
        <header><div><strong>Historial de indexado</strong><small>{repository.project_path}</small></div><button onClick={onClose}>✕</button></header>
        <div className="freshness-row">
          <div>
            <span>Commit indexado </span>
            {gitLabCommitUrl(repository) ? <a href={gitLabCommitUrl(repository)} target="_blank" rel="noreferrer">{repository.last_commit_sha?.slice(0, 8)} ↗</a> : "—"}
          </div>
          <button onClick={checkFreshness} disabled={checking}>{checking ? "comprobando…" : "comprobar cambios"}</button>
        </div>
        {freshness && <div className={`freshness-badge ${freshness.stale ? "stale" : "current"}`}>{freshness.stale ? `Hay cambios (${freshness.remote_sha.slice(0, 8)})` : "Wiki al día"}</div>}
        {error && <div className="inline-error">{error}</div>}
        {loading ? <p>Cargando…</p> : (
          <ol className="job-list">{jobs.map((job) => (
            <li key={job.job_id}>
              <span className={`job-status ${job.status}`}>{job.status}</span>
              <div><strong>{job.current_step || `Job #${job.job_id}`}</strong><small>{job.created_at ? new Date(job.created_at).toLocaleString() : ""}</small>{job.error_message && <em>{job.error_message}</em>}</div>
            </li>
          ))}</ol>
        )}
      </section>
    </div>
  );
}

// frontend/src/app/components/job-history-panel/job-history-panel.component.ts
import {
  Component,
  Output,
  EventEmitter,
  signal,
  inject,
  AfterViewInit,
} from '@angular/core';
import { ApiService, IndexJobResponse } from '../../services/api.service';
import { RepoService } from '../../services/repo.service';
import { gitLabCommitUrl } from '../../utils/gitlab-url';

@Component({
  selector: 'app-job-history-panel',
  standalone: true,
  imports: [],
  templateUrl: './job-history-panel.component.html',
  styleUrls: ['./job-history-panel.component.css'],
})
export class JobHistoryPanelComponent implements AfterViewInit {
  @Output() close = new EventEmitter<void>();

  private api = inject(ApiService);
  private repoService = inject(RepoService);
  private trapRef!: HTMLElement;

  repository = this.repoService.repository;
  jobs = signal<IndexJobResponse[]>([]);
  loading = signal(true);
  error = signal('');
  freshness = signal<{ stale: boolean; remote_sha: string } | null>(null);
  checking = signal(false);

  @ViewChild('trapEl') set trapEl(el: any) {
    if (el) {
      this.trapRef = el.nativeElement;
      this.trapFocus();
    }
  }

  constructor() {
    this.loadJobs();
  }

  ngAfterViewInit(): void {
    this.trapFocus();
  }

  private loadJobs(): void {
    const repo = this.repository() as { id: number } | null;
    if (!repo) return;

    this.api.listRepositoryJobs(repo.id).subscribe({
      next: (jobs) => {
        this.jobs.set(jobs);
        this.loading.set(false);
      },
      error: (err: Error) => {
        this.error.set(err.message);
        this.loading.set(false);
      },
    });
  }

  async checkFreshness(): Promise<void> {
    const repo = this.repository() as { id: number } | null;
    if (!repo) return;

    this.checking.set(true);
    this.error.set('');
    try {
      const result: any = await this.api.checkRepositoryStaleness(repo.id).toPromise();
      this.freshness.set(result);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Error desconocido';
      this.error.set(msg);
    } finally {
      this.checking.set(false);
    }
  }

  onOverlayClick(): void {
    this.close.emit();
  }

  onModalClick(e: MouseEvent): void {
    e.stopPropagation();
  }

  gitLabCommitUrl(): string | null {
    const repo = this.repository() as Record<string, unknown> | null;
    if (!repo) return null;
    return gitLabCommitUrl(repo as any);
  }

  private trapFocus(): void {
    if (!this.trapRef) return;
    const focusable = this.trapRef.querySelectorAll<HTMLElement>(
      'button, input, [tabindex]:not([tabindex="-1"])'
    );
    if (focusable.length === 0) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];

    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        this.close.emit();
        return;
      }
      if (e.key !== 'Tab') return;
      if (e.shiftKey) {
        if (document.activeElement === first) {
          e.preventDefault();
          last.focus();
        }
      } else {
        if (document.activeElement === last) {
          e.preventDefault();
          first.focus();
        }
      }
    };

    this.trapRef.addEventListener('keydown', handler);
  }
}

<div class="modal-overlay" (click)="onOverlayClick()">
  <section #trapEl class="history-panel" role="dialog" aria-modal="true" aria-label="Historial de indexado" (click)="onModalClick($event)">
    @if (repository(); as repo) {
      <header>
        <div>
          <strong>Historial de indexado</strong>
          <small>{{ (repo as any).project_path }}</small>
        </div>
        <button (click)="close.emit()">✕</button>
      </header>

      <div class="freshness-row">
        <div>
          <span>Commit indexado </span>
          @if (gitLabCommitUrl(); as url) {
            <a [href]="url" target="_blank" rel="noreferrer">{{ (repo as any).last_commit_sha?.slice(0, 8) }} ↗</a>
          } @else {
            —
          }
        </div>
        <button (click)="checkFreshness()" [disabled]="checking()">
          {{ checking() ? 'comprobando…' : 'comprobar cambios' }}
        </button>
      </div>

      @if (freshness(); as f) {
        <div class="freshness-badge" [class.stale]="f.stale" [class.current]="!f.stale">
          {{ f.stale ? 'Hay cambios (' + f.remote_sha.slice(0, 8) + ')' : 'Wiki al día' }}
        </div>
      }

      @if (error()) {
        <div class="inline-error">{{ error() }}</div>
      }

      @if (loading()) {
        <p>Cargando…</p>
      } @else {
        <ol class="job-list">
          @for (job of jobs(); track job.job_id) {
            <li>
              <span class="job-status" [class.done]="job.status === 'done'" [class.failed]="job.status === 'failed'">
                {{ job.status }}
              </span>
              <div>
                <strong>{{ job.current_step || 'Job #' + job.job_id }}</strong>
                <small>{{ job.created_at ? (job.created_at | date: 'short') : '' }}</small>
                @if (job.error_message) {
                  <em>{{ job.error_message }}</em>
                }
              </div>
            </li>
          }
        </ol>
      }
    }
  </section>
</div>
