// frontend/src/app/components/code-search/code-search.component.ts
import {
  Component,
  Output,
  EventEmitter,
  signal,
  inject,
  ElementRef,
  ViewChild,
  AfterViewInit,
} from '@angular/core';
import { ApiService, CodeSource } from '../../services/api.service';
import { RepoService } from '../../services/repo.service';
import { languageFromPath } from '../../utils/language';
import { gitLabSourceUrl } from '../../utils/gitlab-url';
import { HighlightedCodeComponent } from '../highlighted-code/highlighted-code.component';

interface LineProps {
  style?: Record<string, string>;
}

@Component({
  selector: 'app-code-search',
  standalone: true,
  imports: [HighlightedCodeComponent],
  templateUrl: './code-search.component.html',
  styleUrls: ['./code-search.component.css'],
})
export class CodeSearchComponent implements AfterViewInit {
  @Output() close = new EventEmitter<void>();

  @ViewChild('searchInput') searchInputRef!: ElementRef<HTMLInputElement>;

  private api = inject(ApiService);
  private repoService = inject(RepoService);
  private trapRef!: HTMLElement;

  repository = this.repoService.repository;
  query = signal('');
  results = signal<CodeSource[] | null>(null);
  loading = signal(false);
  error = signal('');

  @ViewChild('trapEl') set trapEl(el: ElementRef<HTMLElement>) {
    if (el) {
      this.trapRef = el.nativeElement;
      this.trapFocus();
    }
  }

  ngAfterViewInit(): void {
    setTimeout(() => this.searchInputRef?.nativeElement?.focus(), 50);
  }

  private trapFocus(): void {
    if (!this.trapRef) return;
    const focusable = this.trapRef.querySelectorAll<HTMLElement>(
      'button, input, [tabindex]:not([tabindex="-1"])'
    );
    if (focusable.length === 0) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];

    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        this.close.emit();
        return;
      }
      if (e.key !== 'Tab') return;
      if (e.shiftKey) {
        if (document.activeElement === first) {
          e.preventDefault();
          last.focus();
        }
      } else {
        if (document.activeElement === last) {
          e.preventDefault();
          first.focus();
        }
      }
    };

    this.trapRef.addEventListener('keydown', handler);
  }

  get ragAvailable(): boolean {
    const repo = this.repository() as Record<string, unknown> | null;
    return !!repo?.['indexed_in_qdrant'];
  }

  async handleSearch(e: Event): Promise<void> {
    e.preventDefault();
    const q = this.query().trim();
    if (!q || this.loading()) return;

    const repo = this.repository() as { id: number } | null;
    if (!repo) return;

    this.loading.set(true);
    this.error.set('');
    try {
      const res = await this.api.searchCode(repo.id, q).toPromise();
      this.results.set(res?.results ?? []);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'No se pudo completar la búsqueda.';
      this.error.set(msg);
      this.results.set(null);
    } finally {
      this.loading.set(false);
    }
  }

  onOverlayClick(): void {
    this.close.emit();
  }

  onModalClick(e: MouseEvent): void {
    e.stopPropagation();
  }

  expanded = signal<Set<number>>(new Set());

  toggleExpand(index: number): void {
    const s = this.expanded();
    if (s.has(index)) {
      s.delete(index);
    } else {
      s.add(index);
    }
    this.expanded.set(new Set(s));
  }

  matchingLineNumbers(content: string, query: string, startLine: number): Set<number> {
    if (!query) return new Set();
    const lower = query.toLowerCase();
    const lines = content.split('\n');
    const matched = new Set<number>();
    lines.forEach((line, i) => {
      if (line.toLowerCase().includes(lower)) matched.add(startLine + i);
    });
    return matched;
  }

  linePropsFn(content: string, query: string, startLine: number) {
    const matched = this.matchingLineNumbers(content, query, startLine);
    return (lineNumber: number): LineProps =>
      matched.has(lineNumber)
        ? { style: { display: 'block', backgroundColor: 'rgba(255,210,0,0.12)', borderLeft: '2px solid rgba(255,210,0,0.5)' } }
        : { style: { display: 'block' } };
  }

  languageFromPath(path: string): string {
    return languageFromPath(path);
  }

  gitLabSourceUrl(filePath: string, startLine?: number, endLine?: number): string | null {
    const repo = this.repository() as Record<string, unknown> | null;
    if (!repo) return null;
    return gitLabSourceUrl(repo as any, filePath, startLine, endLine);
  }
}

<div class="overlay" (click)="onOverlayClick()">
  <div #trapEl class="modal" role="dialog" aria-modal="true" aria-label="Buscar en el código" (click)="onModalClick($event)">
    <div class="header">
      <span class="title">buscar en el código</span>
      <button class="close-btn" (click)="close.emit()">✕</button>
    </div>

    @if (!ragAvailable) {
      <div class="unavailable">
        La búsqueda semántica no está disponible para este repositorio (el código no
        se pudo indexar en Qdrant). Puedes seguir usando el chat sobre el wiki.
      </div>
    } @else {
      <form class="search-row" (submit)="handleSearch($event)">
        <input
          #searchInput
          [value]="query()"
          (input)="query.set($any($event.target).value)"
          placeholder="ej. dónde se valida el token de autenticación"
          class="input"
        />
        <button type="submit" class="search-btn" [disabled]="loading()">
          {{ loading() ? 'buscando…' : 'buscar' }}
        </button>
      </form>

      @if (error()) {
        <div class="error-box">{{ error() }}</div>
      }

      <div class="results-area">
        @if (results() === null && !error()) {
          <p class="hint">
            Busca por significado, no solo por texto exacto — ej. "manejo de errores de
            red" encontrará código relevante aunque no contenga esas palabras literalmente.
          </p>
        }
        @if (results()?.length === 0) {
          <p class="hint">Sin resultados relevantes.</p>
        }
        @for (r of results(); track r.file_path; let i = $index) {
          <div class="result-card">
            <button class="result-header" (click)="toggleExpand(i)">
              <span class="result-chevron">{{ expanded().has(i) ? '▾' : '▸' }}</span>
              <span class="result-path">{{ r.file_path }}</span>
              <span class="result-lines">L{{ r.start_line }}-{{ r.end_line }}</span>
              @if (matchingLineNumbers(r.content, query(), r.start_line).size > 0; as count) {
                <span class="match-count">{{ count }} coincidencia{{ count !== 1 ? 's' : '' }}</span>
              }
              <span class="result-score">{{ (r.score * 100).toFixed(0) }}%</span>
            </button>
            @if (expanded().has(i)) {
              <app-highlighted-code
                [language]="languageFromPath(r.file_path)"
                [showLineNumbers]="true"
                [startingLineNumber]="r.start_line"
                [wrapLines]="true"
                [lineProps]="linePropsFn(r.content, query(), r.start_line)"
                [customStyle]="{ margin: '0', fontSize: '12px', borderTop: '1px solid var(--border-subtle)', borderRadius: '0' }"
              >{{ r.content }}</app-highlighted-code>
            }
            @if (gitLabSourceUrl(r.file_path, r.start_line, r.end_line); as url) {
              <a [href]="url" target="_blank" rel="noreferrer" class="source-link">abrir en GitLab ↗</a>
            }
          </div>
        }
      </div>
    }
  </div>
</div>

// frontend/src/components/CodeSearch.jsx
import { useState } from "react";
import { api } from "../api/client";
import { useFocusTrap } from "../hooks/useFocusTrap";
import { languageFromPath } from "../utils/language";
import { gitLabSourceUrl } from "../utils/gitlab";
import { HighlightedCode } from "./HighlightedCode";

function matchingLineNumbers(content, query, startLine) {
  if (!query) return new Set();
  const lower = query.toLowerCase();
  const lines = content.split("\n");
  const matched = new Set();
  lines.forEach((line, i) => {
    if (line.toLowerCase().includes(lower)) matched.add(startLine + i);
  });
  return matched;
}

function ResultCard({ result, query, repository }) {
  const [expanded, setExpanded] = useState(true);
  const matchedLines = matchingLineNumbers(result.content, query, result.start_line);

  return (
    <div style={styles.resultCard}>
      <button onClick={() => setExpanded((v) => !v)} style={styles.resultHeader}>
        <span style={styles.resultChevron}>{expanded ? "▾" : "▸"}</span>
        <span style={styles.resultPath}>{result.file_path}</span>
        <span style={styles.resultLines}>
          L{result.start_line}-{result.end_line}
        </span>
        {matchedLines.size > 0 && (
          <span style={styles.matchCount}>{matchedLines.size} coincidencia{matchedLines.size !== 1 ? "s" : ""}</span>
        )}
        <span style={styles.resultScore}>{(result.score * 100).toFixed(0)}%</span>
      </button>
      {expanded && (
        <HighlightedCode
          language={languageFromPath(result.file_path)}
          showLineNumbers
          startingLineNumber={result.start_line}
          wrapLines
          lineProps={(lineNumber) =>
            matchedLines.has(lineNumber)
              ? { style: { display: "block", backgroundColor: "rgba(255,210,0,0.12)", borderLeft: "2px solid rgba(255,210,0,0.5)" } }
              : { style: { display: "block" } }
          }
          customStyle={{ margin: 0, fontSize: 12, borderTop: "1px solid var(--border-subtle)", borderRadius: 0 }}
        >
          {result.content}
        </HighlightedCode>
      )}
      {gitLabSourceUrl(repository, result.file_path, result.start_line, result.end_line) && (
        <a href={gitLabSourceUrl(repository, result.file_path, result.start_line, result.end_line)} target="_blank" rel="noreferrer" style={styles.sourceLink}>
          abrir en GitLab ↗
        </a>
      )}
    </div>
  );
}

/**
 * Buscador global de código: como un "grep semántico" sobre el repo indexado.
 * A diferencia de AskPanel, no llama al LLM — solo recupera y muestra los chunks
 * de código más relevantes, así que la respuesta es instantánea y no genera texto nuevo.
 */
export function CodeSearch({ repositoryId, repository, ragAvailable, onClose }) {
  const trapRef = useFocusTrap();
  const [query, setQuery] = useState("");
  const [results, setResults] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleSearch = async (e) => {
    e.preventDefault();
    const q = query.trim();
    if (!q || loading) return;

    setLoading(true);
    setError("");
    try {
      const res = await api.searchCode(repositoryId, q);
      setResults(res.results);
    } catch (err) {
      setError(err.message || "No se pudo completar la búsqueda.");
      setResults(null);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={styles.overlay} onClick={onClose}>
      <div ref={trapRef} style={styles.modal} role="dialog" aria-modal="true" aria-label="Buscar en el código" onClick={(e) => e.stopPropagation()}>
        <div style={styles.header}>
          <span style={styles.title}>buscar en el código</span>
          <button onClick={onClose} style={styles.closeBtn}>
            ✕
          </button>
        </div>

        {!ragAvailable ? (
          <div style={styles.unavailable}>
            La búsqueda semántica no está disponible para este repositorio (el código no
            se pudo indexar en Qdrant). Puedes seguir usando el chat sobre el wiki.
          </div>
        ) : (
          <>
            <form onSubmit={handleSearch} style={styles.searchRow}>
              <input
                autoFocus
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="ej. dónde se valida el token de autenticación"
                style={styles.input}
              />
              <button type="submit" style={styles.searchBtn} disabled={loading}>
                {loading ? "buscando…" : "buscar"}
              </button>
            </form>

            {error && <div style={styles.errorBox}>{error}</div>}

            <div style={styles.resultsArea}>
              {results === null && !error && (
                <p style={styles.hint}>
                  Busca por significado, no solo por texto exacto — ej. "manejo de errores de
                  red" encontrará código relevante aunque no contenga esas palabras literalmente.
                </p>
              )}
              {results?.length === 0 && <p style={styles.hint}>Sin resultados relevantes.</p>}
              {results?.map((r, i) => (
                <ResultCard key={`${r.file_path}-${i}`} result={r} query={query} repository={repository} />
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
}

const styles = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.55)",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    paddingTop: "8vh",
    zIndex: 50,
  },
  modal: {
    width: "100%",
    maxWidth: 640,
    maxHeight: "78vh",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 12,
    boxShadow: "0 16px 48px rgba(0,0,0,0.5)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 16px",
    borderBottom: "1px solid var(--border-subtle)",
  },
  title: {
    fontSize: 12,
    letterSpacing: "0.05em",
    color: "var(--text-secondary)",
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: "var(--text-tertiary)",
    fontSize: 14,
    cursor: "pointer",
  },
  unavailable: {
    padding: "20px 16px",
    fontFamily: "var(--font-serif)",
    fontSize: 14,
    lineHeight: 1.6,
    color: "var(--text-secondary)",
  },
  searchRow: {
    display: "flex",
    gap: 8,
    padding: 14,
    borderBottom: "1px solid var(--border-subtle)",
  },
  input: {
    flex: 1,
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    padding: "10px 12px",
    fontSize: 13,
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    outline: "none",
  },
  searchBtn: {
    background: "var(--accent-rust)",
    border: "none",
    borderRadius: 6,
    padding: "0 16px",
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--accent-on-rust)",
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  errorBox: {
    margin: "0 14px",
    marginTop: 12,
    background: "rgba(192,89,74,0.12)",
    border: "1px solid var(--accent-red)",
    borderRadius: 6,
    padding: "8px 12px",
    fontSize: 12,
    color: "var(--text-error)",
  },
  resultsArea: {
    flex: 1,
    overflowY: "auto",
    padding: 14,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  hint: {
    fontFamily: "var(--font-serif)",
    fontSize: 13,
    color: "var(--text-tertiary)",
    lineHeight: 1.6,
    margin: 0,
  },
  resultCard: {
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    overflow: "hidden",
    background: "var(--code-bg)",
  },
  resultHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "var(--bg-elevated-2)",
    border: "none",
    padding: "7px 10px",
    fontSize: 11.5,
    fontFamily: "var(--font-mono)",
    textAlign: "left",
  },
  resultChevron: {
    color: "var(--text-tertiary)",
    fontSize: 10,
    flexShrink: 0,
  },
  resultPath: {
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  },
  resultLines: {
    color: "var(--text-tertiary)",
    flexShrink: 0,
  },
  resultScore: {
    color: "var(--accent-sage)",
    flexShrink: 0,
    fontWeight: 600,
  },
  matchCount: {
    fontSize: 10,
    color: "rgba(255,210,0,0.8)",
    flexShrink: 0,
    fontFamily: "var(--font-mono)",
  },
  sourceLink: {
    display: "block",
    padding: "6px 10px",
    borderTop: "1px solid var(--border-subtle)",
    color: "var(--accent-rust)",
    fontSize: 10.5,
    textDecoration: "none",
  },
};
