// frontend/src/app/components/repository-browser/repository-browser.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { Router } from '@angular/router';
import { RepoService } from '../../services/repo.service';
import { GroupService } from '../../services/group.service';
import { GroupBrowserComponent } from '../group-browser/group-browser.component';
import type { RepositorySummary } from '../../services/api.service';

@Component({
  selector: 'app-repository-browser',
  imports: [GroupBrowserComponent],
  templateUrl: './repository-browser.component.html',
  styleUrls: ['./repository-browser.component.css'],
  standalone: true,
})
export class RepositoryBrowserComponent implements OnInit {
  tab = signal<'repos' | 'groups'>('repos');
  deletingId = signal<number | null>(null);

  constructor(
    public repoService: RepoService,
    public groupService: GroupService,
    public router: Router,
  ) {}

  ngOnInit(): void {
    this.repoService.loadRepositories();
    this.groupService.loadGroups();
  }

  handleOpen(repo: RepositorySummary): void {
    this.repoService.openExistingRepository(repo);
  }

  handleDelete(event: Event, repoId: number): void {
    event.stopPropagation();
    if (this.deletingId() !== null) return;
    if (!window.confirm('¿Eliminar este repositorio indexado y su wiki local?')) return;
    this.deletingId.set(repoId);
    this.repoService.handleDeleteRepository(repoId);
    this.deletingId.set(null);
  }

  handleReindex(event: Event, repo: RepositorySummary): void {
    event.stopPropagation();
    this.repoService.handleReindexRepository(repo);
    this.router.navigate(['/connect']);
  }

  handleNewRepo(): void {
    this.repoService.handleReindexRepository(null);
    this.router.navigate(['/connect']);
  }

  handleNewGroup(): void {
    this.groupService.handleReindexGroup(null);
    this.router.navigate(['/group/connect']);
  }

  loadMore(): void {
    this.repoService.loadMoreRepositories();
  }

  setTab(value: 'repos' | 'groups'): void {
    this.tab.set(value);
  }

  reloadPage(): void {
    window.location.reload();
  }
}

<div class="wrapper">
  <div class="card">
    <div class="eyebrow">
      <span class="dot"></span>
      DeepWiki · GitLab
    </div>

    <div class="tabBar">
      <button
        class="tabBtn"
        [class.tabBtnActive]="tab() === 'repos'"
        (click)="setTab('repos')"
      >
        Repositorios
      </button>
      <button
        class="tabBtn"
        [class.tabBtnActive]="tab() === 'groups'"
        (click)="setTab('groups')"
      >
        Grupos
      </button>
    </div>

    @if (tab() === 'repos') {
      <div class="headerRow">
        <h1 class="title">Repositorios indexados</h1>
        <button class="newBtn" (click)="handleNewRepo()">
          + indexar nuevo repo
        </button>
      </div>

      @if (repoService.browseLoading()) {
        <p class="hint">Cargando repositorios…</p>
      }

      @if (repoService.browseError(); as err) {
        <div class="errorBox">
          {{ err }}
          <button class="inlineRetry" (click)="reloadPage()">reintentar</button>
        </div>
      }

      @if (!repoService.browseLoading() && !repoService.browseError() && repoService.repositories().length === 0) {
        <div class="emptyState">
          <p class="hint">
            Todavía no has indexado ningún repositorio. Conecta uno de GitLab para generar
            su wiki por primera vez.
          </p>
          <button class="submitBtn" (click)="handleNewRepo()">
            Indexar mi primer repositorio →
          </button>
        </div>
      }

      @if (!repoService.browseLoading() && repoService.repositories().length > 0) {
        <ul class="list">
          @for (repo of repoService.repositories(); track repo.id) {
            <li class="listItem" (click)="handleOpen(repo)">
              <div class="itemMain">
                <div class="itemName">{{ repo.name }}</div>
                <div class="itemPath">{{ repo.project_path }}</div>
              </div>
              <div class="itemMeta">
                <span class="branchTag">{{ repo.default_branch }}</span>
                <span
                  class="ragTag"
                  [style.color]="repo.indexed_in_qdrant ? 'var(--accent-sage)' : 'var(--text-tertiary)'"
                >
                  ● {{ repo.indexed_in_qdrant ? 'RAG activo' : 'solo wiki' }}
                </span>
                <button
                  class="reindexBtn"
                  (click)="handleReindex($event, repo)"
                  title="Comprobar si hay cambios y reindexar si es necesario"
                >
                  reindexar
                </button>
                <button
                  class="deleteBtn"
                  (click)="handleDelete($event, repo.id)"
                  [disabled]="deletingId() === repo.id"
                  title="Eliminar este repositorio indexado"
                >
                  {{ deletingId() === repo.id ? '…' : 'eliminar' }}
                </button>
              </div>
            </li>
          }
        </ul>
        @if (repoService.hasMoreRepos()) {
          <button
            class="loadMoreBtn"
            (click)="loadMore()"
            [disabled]="repoService.repoLoadingMore()"
          >
            {{ repoService.repoLoadingMore() ? 'Cargando…' : 'Ver más repositorios' }}
          </button>
        }
      }
    }

    @if (tab() === 'groups') {
      <div class="headerRow">
        <h1 class="title">Grupos indexados</h1>
        <button class="newBtn" (click)="handleNewGroup()">
          + indexar grupo
        </button>
      </div>
      <app-group-browser />
    }
  </div>
</div>

// frontend/src/components/RepositoryBrowser.jsx
import { useState } from "react";
import { GroupBrowser } from "./GroupBrowser";

/**
 * Pantalla inicial con dos pestañas: Repositorios y Grupos.
 */
export function RepositoryBrowser({
  repositories, loading, errorMessage, onOpenRepository, onNewRepository, onDeleteRepository, onReindexRepository,
  hasMoreRepos, onLoadMoreRepos, loadingMoreRepos,
  groups, groupsLoading, groupsError, onOpenGroup, onNewGroup, onDeleteGroup, onReindexGroup,
  onRetry,
}) {
  const [tab, setTab] = useState("repos");
  const [deletingId, setDeletingId] = useState(null);

  const handleDelete = async (e, repoId) => {
    e.stopPropagation();
    if (deletingId) return;
    if (!window.confirm("¿Eliminar este repositorio indexado y su wiki local?")) return;
    setDeletingId(repoId);
    try {
      await onDeleteRepository(repoId);
    } finally {
      setDeletingId(null);
    }
  };

  const handleReindex = (e, repo) => {
    e.stopPropagation();
    onReindexRepository(repo);
  };

  return (
    <div style={styles.wrapper} className="repository-browser">
      <div style={styles.card}>
        <div style={styles.eyebrow}>
          <span style={styles.dot} />
          DeepWiki · GitLab
        </div>

        {/* Tab bar */}
        <div style={styles.tabBar}>
          <button
            onClick={() => setTab("repos")}
            style={{ ...styles.tabBtn, ...(tab === "repos" ? styles.tabBtnActive : {}) }}
          >
            Repositorios
          </button>
          <button
            onClick={() => setTab("groups")}
            style={{ ...styles.tabBtn, ...(tab === "groups" ? styles.tabBtnActive : {}) }}
          >
            Grupos
          </button>
        </div>

        {/* ---- Repos tab ---- */}
        {tab === "repos" && (
          <>
            <div style={styles.headerRow} className="browser-header-row">
              <h1 style={styles.title}>Repositorios indexados</h1>
              <button onClick={onNewRepository} style={styles.newBtn}>
                + indexar nuevo repo
              </button>
            </div>

            {loading && <p style={styles.hint}>Cargando repositorios…</p>}
            {errorMessage && <div style={styles.errorBox}>{errorMessage} {onRetry && <button className="inline-retry" onClick={onRetry}>reintentar</button>}</div>}

            {!loading && !errorMessage && repositories.length === 0 && (
              <div style={styles.emptyState}>
                <p style={styles.hint}>
                  Todavía no has indexado ningún repositorio. Conecta uno de GitLab para generar
                  su wiki por primera vez.
                </p>
                <button onClick={onNewRepository} style={styles.submitBtn}>
                  Indexar mi primer repositorio →
                </button>
              </div>
            )}

            {!loading && repositories.length > 0 && (
              <>
                <ul style={styles.list}>
                  {repositories.map((repo) => (
                    <li key={repo.id} style={styles.listItem} className="repository-list-item" onClick={() => onOpenRepository(repo)}>
                      <div style={styles.itemMain}>
                        <div style={styles.itemName}>{repo.name}</div>
                        <div style={styles.itemPath}>{repo.project_path}</div>
                      </div>
                      <div style={styles.itemMeta}>
                        <span style={styles.branchTag}>{repo.default_branch}</span>
                        <span
                          style={{
                            ...styles.ragTag,
                            color: repo.indexed_in_qdrant ? "var(--accent-sage)" : "var(--text-tertiary)",
                          }}
                        >
                          ● {repo.indexed_in_qdrant ? "RAG activo" : "solo wiki"}
                        </span>
                        <button
                          onClick={(e) => handleReindex(e, repo)}
                          style={styles.reindexBtn}
                          title="Comprobar si hay cambios y reindexar si es necesario"
                        >
                          reindexar
                        </button>
                        <button
                          onClick={(e) => handleDelete(e, repo.id)}
                          style={styles.deleteBtn}
                          disabled={deletingId === repo.id}
                          title="Eliminar este repositorio indexado"
                        >
                          {deletingId === repo.id ? "…" : "eliminar"}
                        </button>
                      </div>
                    </li>
                  ))}
                </ul>
                {hasMoreRepos && (
                  <button
                    onClick={onLoadMoreRepos}
                    disabled={loadingMoreRepos}
                    style={styles.loadMoreBtn}
                  >
                    {loadingMoreRepos ? "Cargando…" : "Ver más repositorios"}
                  </button>
                )}
              </>
            )}
          </>
        )}

        {/* ---- Groups tab ---- */}
        {tab === "groups" && (
          <>
            <div style={styles.headerRow} className="browser-header-row">
              <h1 style={styles.title}>Grupos indexados</h1>
              <button onClick={onNewGroup} style={styles.newBtn}>
                + indexar grupo
              </button>
            </div>
            <GroupBrowser
              groups={groups || []}
              loading={groupsLoading}
              errorMessage={groupsError}
              onOpenGroup={onOpenGroup}
              onNewGroup={onNewGroup}
              onDeleteGroup={onDeleteGroup}
              onReindexGroup={onReindexGroup}
            />
          </>
        )}
      </div>
    </div>
  );
}

const styles = {
  wrapper: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "32px 20px",
    background:
      "radial-gradient(circle at 20% 0%, rgba(201,124,74,0.08), transparent 45%), var(--bg-base)",
  },
  card: {
    width: "100%",
    maxWidth: 560,
  },
  tabBar: {
    display: "flex",
    gap: 4,
    marginBottom: 28,
    borderBottom: "1px solid var(--border-subtle)",
    paddingBottom: 0,
  },
  tabBtn: {
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    padding: "8px 14px",
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-tertiary)",
    cursor: "pointer",
    marginBottom: -1,
  },
  tabBtnActive: {
    color: "var(--text-primary)",
    fontWeight: 600,
    borderBottom: "2px solid var(--accent-rust)",
  },
  eyebrow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    letterSpacing: "0.06em",
    color: "var(--text-tertiary)",
    marginBottom: 24,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "var(--accent-rust)",
    display: "inline-block",
  },
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 28,
  },
  title: {
    fontFamily: "var(--font-serif)",
    fontSize: 30,
    fontWeight: 600,
    margin: 0,
    color: "var(--text-primary)",
    letterSpacing: "-0.01em",
  },
  newBtn: {
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    padding: "9px 14px",
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--accent-rust)",
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  hint: {
    fontFamily: "var(--font-serif)",
    fontSize: 15,
    lineHeight: 1.6,
    color: "var(--text-secondary)",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    gap: 20,
    alignItems: "flex-start",
  },
  submitBtn: {
    background: "var(--accent-rust)",
    border: "none",
    borderRadius: 6,
    padding: "13px 18px",
    fontSize: 14,
    fontWeight: 600,
    color: "var(--accent-on-rust)",
    cursor: "pointer",
  },
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  listItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 8,
    padding: "14px 16px",
    cursor: "pointer",
  },
  itemMain: {
    minWidth: 0,
    overflow: "hidden",
  },
  itemName: {
    fontFamily: "var(--font-serif)",
    fontSize: 16,
    fontWeight: 600,
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  itemPath: {
    fontSize: 11.5,
    color: "var(--text-tertiary)",
    marginTop: 2,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  itemMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  branchTag: {
    fontSize: 10.5,
    background: "var(--bg-elevated-2)",
    color: "var(--text-secondary)",
    padding: "2px 7px",
    borderRadius: 4,
  },
  ragTag: {
    fontSize: 10.5,
    whiteSpace: "nowrap",
  },
  reindexBtn: {
    background: "none",
    border: "1px solid var(--border-subtle)",
    borderRadius: 4,
    color: "var(--text-secondary)",
    fontSize: 10.5,
    padding: "4px 8px",
    cursor: "pointer",
  },
  deleteBtn: {
    background: "none",
    border: "none",
    color: "var(--text-tertiary)",
    fontSize: 11,
    padding: "4px 6px",
    cursor: "pointer",
  },
  errorBox: {
    background: "rgba(192,89,74,0.12)",
    border: "1px solid var(--accent-red)",
    borderRadius: 6,
    padding: "10px 12px",
    fontSize: 12.5,
    color: "var(--text-error)",
    lineHeight: 1.5,
  },
  loadMoreBtn: {
    marginTop: 12,
    width: "100%",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    padding: "9px 14px",
    fontSize: 12,
    color: "var(--text-secondary)",
    cursor: "pointer",
    fontFamily: "var(--font-mono)",
  },
};
