// frontend/src/app/components/wiki-sidebar/wiki-sidebar.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnInit,
  OnDestroy,
  signal,
  computed,
  inject,
  ElementRef,
  ViewChild,
} from '@angular/core';
import { ApiService, WikiTextSearchResult } from '../../services/api.service';
import { RepoService } from '../../services/repo.service';
import { RepoSettingsPanelComponent } from '../repo-settings-panel/repo-settings-panel.component';
import { Subject, Subscription, debounceTime, distinctUntilChanged, switchMap } from 'rxjs';

interface PageNav {
  slug: string;
  title: string;
  parent_slug: string | null;
}

function groupPages(pages: PageNav[]) {
  const root = pages.filter((p) => !p.parent_slug);
  const modules = pages.filter((p) => p.parent_slug === 'modules');
  return { root, modules };
}

@Component({
  selector: 'app-wiki-sidebar',
  standalone: true,
  imports: [RepoSettingsPanelComponent],
  templateUrl: './wiki-sidebar.component.html',
  styleUrls: ['./wiki-sidebar.component.css'],
})
export class WikiSidebarComponent implements OnInit, OnDestroy {
  @Input() mobileOpen = false;
  @Output() mobileClose = new EventEmitter<void>();
  @Output() reset = new EventEmitter<void>();
  @Output() reindex = new EventEmitter<void>();

  @ViewChild('searchInput') searchInputRef!: ElementRef<HTMLInputElement>;

  private api = inject(ApiService);
  private repoService = inject(RepoService);

  repository = this.repoService.repository;
  pages = this.repoService.pages;
  activeSlug = this.repoService.activeSlug;

  filter = signal('');
  modulesCollapsed = signal(false);
  showSettings = signal(false);
  wikiSearchResults = signal<WikiTextSearchResult[] | null>(null);
  wikiSearchLoading = signal(false);

  private searchSubject = new Subject<string>();
  private searchSub?: Subscription;
  private keydownHandler?: (e: KeyboardEvent) => void;

  readonly q = computed(() => this.filter().trim().toLowerCase());

  readonly grouped = computed(() => groupPages(this.pages() as unknown as PageNav[]));

  readonly filterPage = (p: PageNav) => !this.q() || p.title.toLowerCase().includes(this.q());

  readonly filteredRoot = computed(() =>
    this.grouped().root.filter(this.filterPage)
  );

  readonly filteredModules = computed(() =>
    this.grouped().modules.filter(this.filterPage)
  );

  readonly displayedResults = computed(() =>
    this.q().length >= 2 ? this.wikiSearchResults() : null
  );

  readonly displayedLoading = computed(() =>
    this.q().length >= 2 && this.wikiSearchLoading()
  );

  readonly lastIndexed = computed(() => {
    const repo = this.repository() as Record<string, unknown> | null;
    const updatedAt = repo?.['updated_at'];
    if (!updatedAt) return null;
    const d = new Date(updatedAt as string);
    return d.toLocaleDateString(undefined, {
      month: 'short',
      day: 'numeric',
    } as Intl.DateTimeFormatOptions) + ', ' + d.toLocaleTimeString(undefined, {
      hour: '2-digit',
      minute: '2-digit',
    } as Intl.DateTimeFormatOptions);
  });

  readonly exportUrl = computed(() => {
    const repo = this.repository() as Record<string, unknown> | null;
    return repo ? this.api.getExportUrl(repo['id'] as number) : '';
  });

  readonly htmlExportUrl = computed(() => {
    const repo = this.repository() as Record<string, unknown> | null;
    return repo ? this.api.getHtmlExportUrl(repo['id'] as number) : '';
  });

  ngOnInit(): void {
    // Debounced wiki text search
    this.searchSub = this.searchSubject.pipe(
      debounceTime(400),
      distinctUntilChanged(),
      switchMap(async (q) => {
        if (q.length < 2) return;
        this.wikiSearchLoading.set(true);
        this.wikiSearchResults.set(null);
        const repo = this.repository() as Record<string, unknown> | null;
        if (!repo) return;
        try {
          const results = await this.api.searchWikiText(repo['id'] as number, q).toPromise();
          this.wikiSearchResults.set(results ?? []);
        } catch {
          this.wikiSearchResults.set([]);
        } finally {
          this.wikiSearchLoading.set(false);
        }
      }),
    ).subscribe();

    // Keyboard shortcut: / to focus search, Escape to clear
    this.keydownHandler = (e: KeyboardEvent) => {
      if (e.key === '/' && document.activeElement?.tagName !== 'INPUT' && document.activeElement?.tagName !== 'TEXTAREA') {
        e.preventDefault();
        this.searchInputRef?.nativeElement?.focus();
      }
      if (e.key === 'Escape' && document.activeElement === this.searchInputRef?.nativeElement) {
        this.filter.set('');
        this.searchInputRef?.nativeElement?.blur();
      }
    };
    document.addEventListener('keydown', this.keydownHandler);
  }

  ngOnDestroy(): void {
    this.searchSub?.unsubscribe();
    if (this.keydownHandler) {
      document.removeEventListener('keydown', this.keydownHandler);
    }
  }

  onFilterChange(value: string): void {
    this.filter.set(value);
    this.searchSubject.next(value);
  }

  onSelectPage(slug: string): void {
    this.repoService.setActiveSlug(slug);
    this.filter.set('');
  }

  onClose(): void {
    this.mobileClose.emit();
  }

  onReset(): void {
    this.reset.emit();
  }

  onReindex(): void {
    this.reindex.emit();
  }
}

<aside
  class="wiki-sidebar"
  [class.is-open]="mobileOpen"
>
  <div class="repo-header">
    <div class="top-row">
      <button class="back-btn" (click)="onReset()" title="Ver todos los repositorios indexados">
        ← mis repos
      </button>
      <div class="top-actions">
        <button class="mobile-close-button" (click)="onClose()" aria-label="Cerrar navegación">✕</button>
        <button class="theme-btn" (click)="showSettings.set(true)" title="Configuración del repositorio (prompt, token webhook)">
          ⚙
        </button>
      </div>
    </div>

    @if (repository(); as repo) {
      <div class="repo-name">{{ repo['name'] }}</div>
      <div class="repo-path">{{ repo['project_path'] }}</div>
      <div class="repo-meta">
        <span class="branch-tag">{{ repo['default_branch'] }}</span>
        <span class="sha-tag">{{ (repo['last_commit_sha'] as string)?.slice(0, 8) }}</span>
      </div>
      <div
        class="rag-tag"
        [class.rag-active]="repo['indexed_in_qdrant']"
        [class.rag-inactive]="!repo['indexed_in_qdrant']"
        [title]="repo['indexed_in_qdrant']
          ? 'El código está indexado en Qdrant: las preguntas buscan en el código real'
          : 'El código no se pudo indexar en Qdrant: las preguntas usan solo el wiki generado'"
      >
        <span class="rag-dot">●</span>
        {{ repo['indexed_in_qdrant'] ? 'búsqueda semántica activa' : 'búsqueda semántica no disponible' }}
      </div>

      @if (lastIndexed(); as indexed) {
        <div class="indexed-row">
          <span class="indexed-at">indexado {{ indexed }}</span>
          <button class="reindex-btn" (click)="onReindex()" title="Volver a indexar este repositorio">
            ↺ reindexar
          </button>
        </div>
      }

      <button class="action-btn" (click)="repoService.setSearchOpen(true)">⌕ buscar en el código</button>
      <button class="action-btn" (click)="repoService.setGraphOpen(true)">⊞ grafo de dependencias</button>
      <button class="action-btn" (click)="repoService.setHistoryOpen(true)">◷ historial y frescura</button>
      <div class="export-row">
        <a [href]="exportUrl()" download class="export-btn" title="Descargar como Markdown">↓ .md</a>
        <a [href]="htmlExportUrl()" download class="export-btn" title="Descargar como HTML">↓ .html</a>
        <button class="export-btn" title="Imprimir la página actual / guardar como PDF" (click)="window.print()">⎙ pdf</button>
      </div>
    }
  </div>

  <div class="search-wrap">
    <input
      #searchInput
      type="search"
      placeholder="buscar… (tecla /)"
      [value]="filter()"
      (input)="onFilterChange($any($event.target).value)"
      aria-label="Buscar en el wiki"
    />
    @if (displayedLoading()) {
      <div class="search-spinner">…</div>
    }
  </div>

  <nav class="nav">
    @if (displayedResults(); as results) {
      @if (results.length > 0) {
        <div class="nav-section">
          <div class="nav-section-label">resultados en el wiki</div>
          <div class="nav-group">
            @for (r of results; track r.slug) {
              <button
                class="nav-item nav-search-item"
                [class.active]="r.slug === activeSlug()"
                (click)="onSelectPage(r.slug)"
              >
                <div class="search-title">{{ r.title }}</div>
                <div class="search-excerpt">{{ r.excerpt }}</div>
              </button>
            }
          </div>
        </div>
      } @else if (filter().trim().length >= 2) {
        <div class="no-results">sin resultados para "{{ filter() }}"</div>
      }
    } @else {
      @if (filteredRoot().length === 0 && filteredModules().length === 0) {
        <div class="no-results">sin resultados</div>
      }

      <div class="nav-group">
        @for (page of filteredRoot(); track page.slug) {
          <button
            class="nav-item"
            [class.active]="page.slug === activeSlug()"
            [style.paddingLeft.px]="14"
            (click)="onSelectPage(page.slug)"
          >
            {{ page.title }}
          </button>
        }
      </div>

      @if (filteredModules().length > 0 || (grouped().modules.length > 0 && !filter())) {
        <div class="nav-section">
          <button
            class="section-header"
            (click)="modulesCollapsed.set(!modulesCollapsed())"
            [attr.aria-expanded]="!modulesCollapsed()"
          >
            <span class="nav-section-label">módulos</span>
            <span class="collapse-icon">{{ modulesCollapsed() ? '▶' : '▼' }}</span>
          </button>
          @if (!modulesCollapsed()) {
            <div class="nav-group">
              @for (page of filteredModules(); track page.slug) {
                <button
                  class="nav-item"
                  [class.active]="page.slug === activeSlug()"
                  [style.paddingLeft.px]="28"
                  (click)="onSelectPage(page.slug)"
                >
                  {{ page.title }}
                </button>
              }
            </div>
          }
        </div>
      }

      @if (filter() && filteredModules().length > 0) {
        <div class="nav-section">
          <div class="nav-section-label">módulos</div>
          <div class="nav-group">
            @for (page of filteredModules(); track page.slug) {
              <button
                class="nav-item"
                [class.active]="page.slug === activeSlug()"
                [style.paddingLeft.px]="28"
                (click)="onSelectPage(page.slug)"
              >
                {{ page.title }}
              </button>
            }
          </div>
        </div>
      }
    }
  </nav>

  <div class="key-hint">
    <span>/</span> buscar · <span>Alt+← / Alt+→</span> navegar · <span>?</span> atajos
  </div>
</aside>

@if (showSettings()) {
  <app-repo-settings-panel (close)="showSettings.set(false)" />
}

// frontend/src/components/WikiSidebar.jsx
import { useEffect, useRef, useState } from "react";
import { api } from "../api/client";
import { RepoSettingsPanel } from "./RepoSettingsPanel";
import { styles } from "./WikiSidebar.styles";

function groupPages(pages) {
  const root = pages.filter((p) => !p.parent_slug);
  const modules = pages.filter((p) => p.parent_slug === "modules");
  return { root, modules };
}
export function WikiSidebar({
  repository,
  pages,
  activeSlug,
  onSelectPage,
  onReset,
  onOpenSearch,
  onOpenGraph,
  onReindex,
  onOpenHistory,
  mobileOpen,
  onMobileClose,
  theme,
  onToggleTheme,
}) {
  const [filter, setFilter] = useState("");
  const [modulesCollapsed, setModulesCollapsed] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [wikiSearchResults, setWikiSearchResults] = useState(null);
  const [wikiSearchLoading, setWikiSearchLoading] = useState(false);
  const debounceRef = useRef(null);
  const searchInputRef = useRef(null);
  const exportUrl = api.getExportUrl(repository.id);
  const htmlExportUrl = api.getHtmlExportUrl(repository.id);

  const q = filter.trim().toLowerCase();
  const { root, modules } = groupPages(pages);
  const filterPage = (p) => !q || p.title.toLowerCase().includes(q);
  const filteredRoot = root.filter(filterPage);
  const filteredModules = modules.filter(filterPage);

  // Derived: hide stale results when query is too short without calling setState in effect body
  const displayedResults = q.length >= 2 ? wikiSearchResults : null;
  const displayedLoading = q.length >= 2 && wikiSearchLoading;

  // FTS5 wiki-wide search with 400ms debounce
  useEffect(() => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    if (q.length < 2) {
      return;
    }
    debounceRef.current = setTimeout(async () => {
      setWikiSearchResults(null);
      setWikiSearchLoading(true);
      try {
        const results = await api.searchWikiText(repository.id, q);
        setWikiSearchResults(results);
      } catch {
        setWikiSearchResults([]);
      } finally {
        setWikiSearchLoading(false);
      }
    }, 400);
    return () => clearTimeout(debounceRef.current);
  }, [q, repository.id]);

  // '/' key focuses the search input when in the wiki view
  useEffect(() => {
    const handler = (e) => {
      if (e.key === "/" && document.activeElement?.tagName !== "INPUT" && document.activeElement?.tagName !== "TEXTAREA") {
        e.preventDefault();
        searchInputRef.current?.focus();
      }
      if (e.key === "Escape" && document.activeElement === searchInputRef.current) {
        setFilter("");
        searchInputRef.current?.blur();
      }
    };
    document.addEventListener("keydown", handler);
    return () => document.removeEventListener("keydown", handler);
  }, []);

  const lastIndexed = repository.updated_at
    ? new Date(repository.updated_at).toLocaleString(undefined, {
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })
    : null;

  return (
    <>
    <aside style={styles.sidebar} className={`wiki-sidebar${mobileOpen ? " is-open" : ""}`}>
      <div style={styles.repoHeader}>
        <div style={styles.topRow}>
          <button onClick={onReset} style={styles.backBtn} title="Ver todos los repositorios indexados">
            ← mis repos
          </button>
          <div style={{ display: "flex", gap: 4 }}>
            <button onClick={onMobileClose} style={styles.themeBtn} className="mobile-close-button" aria-label="Cerrar navegación">✕</button>
            <button
              onClick={() => setShowSettings(true)}
              style={styles.themeBtn}
              title="Configuración del repositorio (prompt, token webhook)"
            >
              ⚙
            </button>
            <button
              onClick={onToggleTheme}
              style={styles.themeBtn}
              title={theme === "dark" ? "Cambiar a modo claro" : "Cambiar a modo oscuro"}
            >
              {theme === "dark" ? "☀" : "☾"}
            </button>
          </div>
        </div>

        <div style={styles.repoName}>{repository.name}</div>
        <div style={styles.repoPath}>{repository.project_path}</div>
        <div style={styles.repoMeta}>
          <span style={styles.branchTag}>{repository.default_branch}</span>
          <span style={styles.shaTag}>{repository.last_commit_sha?.slice(0, 8)}</span>
        </div>
        <div
          style={{
            ...styles.ragTag,
            color: repository.indexed_in_qdrant ? "var(--accent-sage)" : "var(--text-tertiary)",
          }}
          title={
            repository.indexed_in_qdrant
              ? "El código está indexado en Qdrant: las preguntas buscan en el código real"
              : "El código no se pudo indexar en Qdrant: las preguntas usan solo el wiki generado"
          }
        >
          <span style={styles.ragDot}>●</span>
          {repository.indexed_in_qdrant ? "búsqueda semántica activa" : "búsqueda semántica no disponible"}
        </div>

        {lastIndexed && onReindex && (
          <div style={styles.indexedRow}>
            <span style={styles.indexedAt}>indexado {lastIndexed}</span>
            <button style={styles.reindexBtn} onClick={() => onReindex(repository)} title="Volver a indexar este repositorio">
              ↺ reindexar
            </button>
          </div>
        )}

        <button onClick={onOpenSearch} style={styles.actionBtn}>
          ⌕ buscar en el código
        </button>
        <button onClick={onOpenGraph} style={styles.actionBtn}>
          ⊞ grafo de dependencias
        </button>
        <button onClick={onOpenHistory} style={styles.actionBtn}>
          ◷ historial y frescura
        </button>
        <div style={styles.exportRow}>
          <a href={exportUrl} download style={styles.exportBtn} title="Descargar como Markdown">
            ↓ .md
          </a>
          <a href={htmlExportUrl} download style={styles.exportBtn} title="Descargar como HTML">
            ↓ .html
          </a>
          <button
            style={styles.exportBtn}
            title="Imprimir la página actual / guardar como PDF"
            onClick={() => window.print()}
          >
            ⎙ pdf
          </button>
        </div>
      </div>

      <div style={styles.searchWrap}>
        <input
          ref={searchInputRef}
          type="search"
          placeholder="buscar… (tecla /)"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          style={styles.searchInput}
          aria-label="Buscar en el wiki"
        />
        {displayedLoading && <div style={styles.searchSpinner}>…</div>}
      </div>

      <nav style={styles.nav}>
        {/* FTS5 full-text search results */}
        {displayedResults && displayedResults.length > 0 && (
          <div style={styles.navSection}>
            <div style={styles.navSectionLabel}>resultados en el wiki</div>
            <div style={styles.navGroup}>
              {displayedResults.map((r) => (
                <button
                  key={r.slug}
                  style={{
                    ...styles.navItem,
                    paddingLeft: 14,
                    background: r.slug === activeSlug ? "var(--bg-elevated-2)" : "transparent",
                    color: r.slug === activeSlug ? "var(--accent-rust)" : "var(--text-secondary)",
                    borderLeft: r.slug === activeSlug ? "2px solid var(--accent-rust)" : "2px solid transparent",
                    display: "block",
                    height: "auto",
                    textAlign: "left",
                  }}
                  onClick={() => { onSelectPage(r.slug); setFilter(""); }}
                >
                  <div style={{ fontSize: 12.5, fontFamily: "var(--font-mono)" }}>{r.title}</div>
                  <div style={styles.searchExcerpt}>{r.excerpt}</div>
                </button>
              ))}
            </div>
          </div>
        )}
        {displayedResults && displayedResults.length === 0 && q.length >= 2 && (
          <div style={styles.noResults}>sin resultados para "{q}"</div>
        )}

        {/* Regular page nav (hidden when showing FTS results) */}
        {!displayedResults && (
          <>
            {filteredRoot.length === 0 && filteredModules.length === 0 && (
              <div style={styles.noResults}>sin resultados</div>
            )}

            <div style={styles.navGroup}>
              {filteredRoot.map((page) => (
                <NavItem
                  key={page.slug}
                  page={page}
                  active={page.slug === activeSlug}
                  onClick={() => onSelectPage(page.slug)}
                />
              ))}
            </div>

            {(filteredModules.length > 0 || modules.length > 0) && !q && (
              <div style={styles.navSection}>
                <button
                  style={styles.sectionHeader}
                  onClick={() => setModulesCollapsed((c) => !c)}
                  aria-expanded={!modulesCollapsed}
                >
                  <span style={styles.navSectionLabel}>módulos</span>
                  <span style={styles.collapseIcon}>{modulesCollapsed ? "▶" : "▼"}</span>
                </button>
                {!modulesCollapsed && (
                  <div style={styles.navGroup}>
                    {modules.map((page) => (
                      <NavItem
                        key={page.slug}
                        page={page}
                        active={page.slug === activeSlug}
                        onClick={() => onSelectPage(page.slug)}
                        indent
                      />
                    ))}
                  </div>
                )}
              </div>
            )}

            {q && filteredModules.length > 0 && (
              <div style={styles.navSection}>
                <div style={styles.navSectionLabel}>módulos</div>
                <div style={styles.navGroup}>
                  {filteredModules.map((page) => (
                    <NavItem
                      key={page.slug}
                      page={page}
                      active={page.slug === activeSlug}
                      onClick={() => onSelectPage(page.slug)}
                      indent
                    />
                  ))}
                </div>
              </div>
            )}
          </>
        )}
      </nav>

      <div style={styles.keyHint}>
        <span>/</span> buscar · <span>Alt+← / Alt+→</span> navegar · <span>?</span> atajos
      </div>
    </aside>
    {showSettings && (
      <RepoSettingsPanel repository={repository} onClose={() => setShowSettings(false)} />
    )}
  </>
  );
}

function NavItem({ page, active, onClick, indent }) {
  return (
    <button
      onClick={onClick}
      style={{
        ...styles.navItem,
        paddingLeft: indent ? 28 : 14,
        background: active ? "var(--bg-elevated-2)" : "transparent",
        color: active ? "var(--accent-rust)" : "var(--text-secondary)",
        borderLeft: active ? "2px solid var(--accent-rust)" : "2px solid transparent",
      }}
    >
      {page.title}
    </button>
  );
}
