// frontend/src/components/AskPanel.jsx
import { useState, useRef, useEffect, useCallback } from "react";
import ReactMarkdown from "react-markdown";
import { api } from "../api/client";
import { languageFromPath } from "../utils/language";
import { gitLabSourceUrl } from "../utils/gitlab";
import { HighlightedCode } from "./HighlightedCode";

const MAX_HISTORY_TURNS = 10;

function CopyButton({ text }) {
  const [copied, setCopied] = useState(false);
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      /* clipboard unavailable */
    }
  };
  return (
    <button onClick={handleCopy} style={styles.copyBtn} title="Copiar respuesta">
      {copied ? "✓" : "⎘"}
    </button>
  );
}

function SourceExtract({ source, repository }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div style={styles.sourceCard}>
      <button onClick={() => setExpanded((v) => !v)} style={styles.sourceHeader}>
        <span style={styles.sourceChevron}>{expanded ? "▾" : "▸"}</span>
        <span style={styles.sourcePath}>{source.file_path}</span>
        <span style={styles.sourceLines}>
          L{source.start_line}-{source.end_line}
        </span>
      </button>
      {expanded && (
        <HighlightedCode
          language={languageFromPath(source.file_path)}
          showLineNumbers
          startingLineNumber={source.start_line}
          customStyle={{
            margin: 0,
            fontSize: 11.5,
            borderTop: "1px solid var(--border-subtle)",
            borderRadius: 0,
            maxHeight: 260,
          }}
        >
          {source.content}
        </HighlightedCode>
      )}
      {gitLabSourceUrl(repository, source.file_path, source.start_line, source.end_line) && (
        <a
          href={gitLabSourceUrl(repository, source.file_path, source.start_line, source.end_line)}
          target="_blank"
          rel="noreferrer"
          style={styles.sourceLink}
        >abrir en GitLab ↗</a>
      )}
    </div>
  );
}

export function AskPanel({ repositoryId, repository, ragAvailable }) {
  const [open, setOpen] = useState(false);
  const [question, setQuestion] = useState("");
  const [messages, setMessages] = useState([]);
  const [loading, setLoading] = useState(false);
  const scrollRef = useRef(null);
  const abortRef = useRef(null);
  const inputRef = useRef(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, loading]);

  // Focus input when panel opens
  useEffect(() => {
    if (open) setTimeout(() => inputRef.current?.focus(), 50);
  }, [open]);

  const handleStop = useCallback(() => {
    abortRef.current?.abort();
  }, []);

  const handleAsk = async (e) => {
    e.preventDefault();
    const q = question.trim();
    if (!q || loading) return;

    // Build history from the last MAX_HISTORY_TURNS user/assistant exchanges
    const history = messages
      .filter((m) => m.role === "user" || m.role === "assistant")
      .slice(-MAX_HISTORY_TURNS * 2)
      .map((m) => ({ role: m.role, content: m.text }));

    setQuestion("");
    setLoading(true);
    setMessages((prev) => [
      ...prev,
      { role: "user", text: q },
      { role: "assistant", text: "", sources: [], streaming: true },
    ]);

    abortRef.current = new AbortController();

    try {
      for await (const event of api.streamAskQuestion(
        repositoryId, q, history, abortRef.current.signal
      )) {
        if (event.token !== undefined) {
          setMessages((prev) => {
            const copy = [...prev];
            const last = copy[copy.length - 1];
            if (last?.streaming) {
              copy[copy.length - 1] = { ...last, text: last.text + event.token };
            }
            return copy;
          });
        } else if (event.sources !== undefined) {
          setMessages((prev) => {
            const copy = [...prev];
            const last = copy[copy.length - 1];
            if (last?.streaming) {
              copy[copy.length - 1] = { ...last, sources: event.sources };
            }
            return copy;
          });
        }
      }
    } catch (err) {
      if (err.name === "AbortError") {
        // User stopped streaming — finalise the partial answer cleanly
        setMessages((prev) => {
          const copy = [...prev];
          const last = copy[copy.length - 1];
          if (last?.streaming) copy[copy.length - 1] = { ...last, streaming: false };
          return copy;
        });
        setLoading(false);
        return;
      }
      setMessages((prev) => {
        const copy = [...prev];
        if (copy[copy.length - 1]?.streaming) {
          copy[copy.length - 1] = { role: "error", text: err.message };
        } else {
          copy.push({ role: "error", text: err.message });
        }
        return copy;
      });
    } finally {
      setMessages((prev) => {
        const copy = [...prev];
        const last = copy[copy.length - 1];
        if (last?.streaming) {
          copy[copy.length - 1] = { ...last, streaming: false };
        }
        return copy;
      });
      setLoading(false);
    }
  };

  const handleClear = () => setMessages([]);

  if (!open) {
    return (
      <button onClick={() => setOpen(true)} style={styles.fab}>
        ¿preguntas sobre este repo?
      </button>
    );
  }

  const streamingMsg = messages[messages.length - 1]?.streaming ? messages[messages.length - 1] : null;

  return (
    <div style={styles.panel}>
      <div style={styles.panelHeader}>
        <span style={styles.panelTitle}>preguntar al repo</span>
        <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
          {messages.length > 0 && !loading && (
            <button onClick={handleClear} style={styles.clearBtn} title="Limpiar conversación">
              limpiar
            </button>
          )}
          <button onClick={() => setOpen(false)} style={styles.closeBtn}>
            ✕
          </button>
        </div>
      </div>

      {!ragAvailable && (
        <div style={styles.degradedBanner}>
          búsqueda semántica sobre código no disponible para este repo — las respuestas se
          basan solo en el wiki generado, sin extractos de código
        </div>
      )}

      <div ref={scrollRef} style={styles.messages}>
        {messages.length === 0 && (
          <div style={styles.emptyHint}>
            {ragAvailable
              ? "Pregunta algo sobre el código real del proyecto. La respuesta incluye los fragmentos de código exactos usados para generarla."
              : "Pregunta algo sobre la arquitectura, un módulo o cómo ejecutar el proyecto, basado en el wiki ya generado."}
          </div>
        )}
        {messages.map((m, i) => (
          <div key={i} style={styles.messageGroup}>
            <div
              style={{
                ...styles.message,
                alignSelf: m.role === "user" ? "flex-end" : "flex-start",
                background: m.role === "user" ? "var(--accent-rust-dim)" : "var(--bg-elevated-2)",
                color: m.role === "error" ? "var(--accent-red)" : "var(--text-primary)",
                position: "relative",
              }}
            >
              {m.role === "assistant" ? <ReactMarkdown>{m.text}</ReactMarkdown> : m.text}
              {m.role === "assistant" && !m.streaming && m.text && (
                <CopyButton text={m.text} />
              )}
            </div>

            {m.role === "assistant" && m.sources?.length > 0 && (
              <div style={styles.sourcesBlock}>
                <div style={styles.sourcesLabel}>
                  código usado para esta respuesta ({m.sources.length})
                </div>
                {m.sources.map((s, si) => (
                  <SourceExtract key={`${s.file_path}-${si}`} source={s} repository={repository} />
                ))}
              </div>
            )}
          </div>
        ))}
        {loading && !streamingMsg && (
          <div style={{ ...styles.message, ...styles.thinking }}>pensando…</div>
        )}
      </div>

      <form onSubmit={handleAsk} style={styles.inputRow}>
        <input
          ref={inputRef}
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          placeholder="¿cómo se autentican los usuarios?"
          style={styles.input}
          disabled={loading}
        />
        {loading ? (
          <button type="button" onClick={handleStop} style={styles.stopBtn}>
            ■ parar
          </button>
        ) : (
          <button type="submit" style={styles.sendBtn} disabled={!question.trim()}>
            enviar
          </button>
        )}
      </form>
    </div>
  );
}

const styles = {
  fab: {
    position: "fixed",
    bottom: 24,
    right: 24,
    background: "var(--accent-rust)",
    color: "var(--accent-on-rust)",
    border: "none",
    borderRadius: 24,
    padding: "12px 20px",
    fontSize: 12.5,
    fontWeight: 600,
    boxShadow: "0 4px 16px rgba(0,0,0,0.4)",
    cursor: "pointer",
  },
  panel: {
    position: "fixed",
    bottom: 24,
    right: 24,
    width: 460,
    height: 560,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 12,
    boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 14px",
    borderBottom: "1px solid var(--border-subtle)",
  },
  panelTitle: {
    fontSize: 11.5,
    letterSpacing: "0.04em",
    color: "var(--text-secondary)",
  },
  clearBtn: {
    background: "none",
    border: "1px solid var(--border-subtle)",
    borderRadius: 4,
    padding: "2px 8px",
    fontSize: 10,
    color: "var(--text-tertiary)",
    cursor: "pointer",
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: "var(--text-tertiary)",
    fontSize: 13,
    cursor: "pointer",
  },
  degradedBanner: {
    fontSize: 11,
    lineHeight: 1.5,
    color: "var(--text-warning)",
    background: "rgba(201,124,74,0.1)",
    borderBottom: "1px solid var(--border-subtle)",
    padding: "8px 14px",
  },
  messages: {
    flex: 1,
    overflowY: "auto",
    padding: 14,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  messageGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  emptyHint: {
    fontFamily: "var(--font-serif)",
    fontSize: 13,
    color: "var(--text-tertiary)",
    lineHeight: 1.6,
  },
  message: {
    maxWidth: "92%",
    padding: "8px 11px",
    borderRadius: 8,
    fontSize: 13,
    lineHeight: 1.5,
  },
  sourcesBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
    alignSelf: "flex-start",
    width: "92%",
  },
  sourcesLabel: {
    fontSize: 10,
    letterSpacing: "0.04em",
    color: "var(--text-tertiary)",
    marginTop: 2,
  },
  sourceCard: {
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    overflow: "hidden",
    background: "var(--code-bg)",
  },
  sourceHeader: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    width: "100%",
    background: "var(--bg-elevated-2)",
    border: "none",
    padding: "6px 10px",
    fontSize: 11,
    fontFamily: "var(--font-mono)",
    textAlign: "left",
    cursor: "pointer",
  },
  sourceChevron: {
    color: "var(--text-tertiary)",
    fontSize: 10,
    flexShrink: 0,
  },
  sourcePath: {
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  },
  sourceLines: {
    color: "var(--text-tertiary)",
    flexShrink: 0,
  },
  sourceLink: {
    display: "block",
    padding: "6px 10px",
    borderTop: "1px solid var(--border-subtle)",
    color: "var(--accent-rust)",
    fontSize: 10.5,
    textDecoration: "none",
  },
  thinking: {
    background: "var(--bg-elevated-2)",
    color: "var(--text-tertiary)",
    fontSize: 12,
  },
  copyBtn: {
    position: "absolute",
    top: 6,
    right: 6,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 4,
    padding: "2px 6px",
    fontSize: 11,
    color: "var(--text-tertiary)",
    cursor: "pointer",
    opacity: 0.7,
  },
  inputRow: {
    display: "flex",
    gap: 8,
    padding: 12,
    borderTop: "1px solid var(--border-subtle)",
  },
  input: {
    flex: 1,
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    padding: "8px 10px",
    fontSize: 12.5,
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    outline: "none",
  },
  sendBtn: {
    background: "var(--accent-rust)",
    border: "none",
    borderRadius: 6,
    padding: "0 14px",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--accent-on-rust)",
    cursor: "pointer",
  },
  stopBtn: {
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-strong)",
    borderRadius: 6,
    padding: "0 12px",
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--accent-red, #c05a4a)",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
};

// frontend/src/app/components/ask-panel/ask-panel.component.ts
import {
  Component,
  signal,
  inject,
  ElementRef,
  ViewChild,
  AfterViewChecked,
  OnDestroy,
} from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { Subscription } from 'rxjs';
import { ApiService, StreamEvent, CodeSource } from '../../services/api.service';
import { RepoService } from '../../services/repo.service';
import { gitLabSourceUrl } from '../../utils/gitlab-url';
import { languageFromPath } from '../../utils/language';
import { HighlightedCodeComponent } from '../highlighted-code/highlighted-code.component';

interface ChatMessage {
  role: 'user' | 'assistant' | 'error';
  text: string;
  sources?: CodeSource[];
  streaming?: boolean;
}

@Component({
  selector: 'app-ask-panel',
  standalone: true,
  imports: [HighlightedCodeComponent],
  templateUrl: './ask-panel.component.html',
  styleUrls: ['./ask-panel.component.css'],
})
export class AskPanelComponent implements AfterViewChecked, OnDestroy {
  @ViewChild('scrollContainer') scrollRef!: ElementRef<HTMLElement>;
  @ViewChild('inputEl') inputRef!: ElementRef<HTMLInputElement>;

  private api = inject(ApiService);
  private repoService = inject(RepoService);
  private sanitizer = inject(DomSanitizer);

  repository = this.repoService.repository;
  repositoryId = signal<number | undefined>(undefined);
  ragAvailable = signal(false);

  open = signal(false);
  question = signal('');
  messages = signal<ChatMessage[]>([]);
  loading = signal(false);

  private streamSub?: Subscription;
  private abortController?: AbortController;

  constructor() {
    const repo = this.repository();
    if (repo) {
      const r = repo as { id: number; indexed_in_qdrant?: boolean };
      this.repositoryId.set(r.id);
      this.ragAvailable.set(!!r.indexed_in_qdrant);
    }
  }

  ngAfterViewChecked(): void {
    if (this.scrollRef) {
      this.scrollRef.nativeElement.scrollTop = this.scrollRef.nativeElement.scrollHeight;
    }
  }

  ngOnDestroy(): void {
    this.streamSub?.unsubscribe();
  }

  onOpen(): void {
    this.open.set(true);
    setTimeout(() => this.inputRef?.nativeElement?.focus(), 50);
  }

  onClose(): void {
    this.open.set(false);
  }

  onStop(): void {
    this.abortController?.abort();
  }

  async onAsk(e: Event): Promise<void> {
    e.preventDefault();
    const q = this.question().trim();
    if (!q || this.loading()) return;

    const repoId = this.repositoryId();
    if (!repoId) return;

    this.question.set('');
    this.loading.set(true);

    this.messages.update((prev) => [
      ...prev,
      { role: 'user', text: q },
      { role: 'assistant', text: '', sources: [], streaming: true },
    ]);

    this.abortController = new AbortController();

    try {
      this.streamSub = this.api
        .streamAskQuestion(repoId, q, [])
        .subscribe({
          next: (event: StreamEvent) => {
            if (event.token !== undefined) {
              this.messages.update((prev) => {
                const copy = [...prev];
                const last = copy[copy.length - 1];
                if (last?.streaming) {
                  copy[copy.length - 1] = { ...last, text: last.text + event.token };
                }
                return copy;
              });
            } else if (event.sources !== undefined) {
              this.messages.update((prev) => {
                const copy = [...prev];
                const last = copy[copy.length - 1];
                if (last?.streaming) {
                  copy[copy.length - 1] = { ...last, sources: event.sources };
                }
                return copy;
              });
            }
          },
          error: (err: Error) => {
            this.messages.update((prev) => {
              const copy = [...prev];
              if (copy[copy.length - 1]?.streaming) {
                copy[copy.length - 1] = { role: 'error', text: err.message };
              } else {
                copy.push({ role: 'error', text: err.message });
              }
              return copy;
            });
            this.loading.set(false);
          },
          complete: () => {
            this.messages.update((prev) => {
              const copy = [...prev];
              const last = copy[copy.length - 1];
              if (last?.streaming) {
                copy[copy.length - 1] = { ...last, streaming: false };
              }
              return copy;
            });
            this.loading.set(false);
          },
        });
    } catch {
      this.loading.set(false);
    }
  }

  onClear(): void {
    this.messages.set([]);
  }

  markdownToHtml(text: string): SafeHtml {
    let html = text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/`([^`]+)`/g, '<code class="inline-code">$1</code>')
      .replace(
        /\[([^\]]+)\]\(([^)]+)\)/g,
        '<a href="$2" target="_blank" rel="noreferrer">$1</a>',
      )
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br>');

    html = '<p>' + html + '</p>';
    html = html.replace(/<p>\s*<\/p>/g, '');
    return this.sanitizer.bypassSecurityTrustHtml(html);
  }

  async copyText(text: string): Promise<void> {
    try {
      await navigator.clipboard.writeText(text);
    } catch { /* ignore */ }
  }

  sourceExpanded = signal<Set<string>>(new Set());

  toggleSource(key: string): void {
    const s = this.sourceExpanded();
    if (s.has(key)) {
      s.delete(key);
    } else {
      s.add(key);
    }
    this.sourceExpanded.set(new Set(s));
  }

  gitLabSourceUrl(filePath: string, startLine?: number, endLine?: number): string | null {
    const repo = this.repository() as Record<string, unknown> | null;
    if (!repo) return null;
    return gitLabSourceUrl(repo as any, filePath, startLine, endLine);
  }

  languageFromPath(path: string): string {
    return languageFromPath(path);
  }
}

@if (!open()) {
  <button class="fab" (click)="onOpen()">
    ¿preguntas sobre este repo?
  </button>
} @else {
  <div class="panel">
    <div class="panel-header">
      <span class="panel-title">preguntar al repo</span>
      <div class="header-actions">
        @if (messages().length > 0 && !loading()) {
          <button class="clear-btn" (click)="onClear()" title="Limpiar conversación">
            limpiar
          </button>
        }
        <button class="close-btn" (click)="onClose()">✕</button>
      </div>
    </div>

    @if (!ragAvailable()) {
      <div class="degraded-banner">
        búsqueda semántica sobre código no disponible para este repo — las respuestas se
        basan solo en el wiki generado, sin extractos de código
      </div>
    }

    <div #scrollContainer class="messages">
      @if (messages().length === 0) {
        <div class="empty-hint">
          @if (ragAvailable()) {
            Pregunta algo sobre el código real del proyecto. La respuesta incluye los fragmentos de código exactos usados para generarla.
          } @else {
            Pregunta algo sobre la arquitectura, un módulo o cómo ejecutar el proyecto, basado en el wiki ya generado.
          }
        </div>
      }

      @for (m of messages(); track $index) {
        <div class="message-group">
          <div
            class="message"
            [class.message-user]="m.role === 'user'"
            [class.message-assistant]="m.role === 'assistant'"
            [class.message-error]="m.role === 'error'"
          >
            @if (m.role === 'assistant') {
              <div class="markdown-body" [innerHTML]="markdownToHtml(m.text)"></div>
              @if (!m.streaming && m.text) {
                <button class="copy-btn" (click)="copyText(m.text)" title="Copiar respuesta">⎘</button>
              }
            } @else {
              {{ m.text }}
            }
          </div>

          @if (m.role === 'assistant' && m.sources && m.sources.length > 0) {
            <div class="sources-block">
              <div class="sources-label">código usado para esta respuesta ({{ m.sources.length }})</div>
              @for (s of m.sources; track s.file_path; let si = $index) {
                <div class="source-card">
                  <button class="source-header" (click)="toggleSource(s.file_path + '-' + si)">
                    <span class="source-chevron">{{ sourceExpanded().has(s.file_path + '-' + si) ? '▾' : '▸' }}</span>
                    <span class="source-path">{{ s.file_path }}</span>
                    <span class="source-lines">L{{ s.start_line }}-{{ s.end_line }}</span>
                  </button>
                  @if (sourceExpanded().has(s.file_path + '-' + si)) {
                    <app-highlighted-code
                      [language]="languageFromPath(s.file_path)"
                      [showLineNumbers]="true"
                      [startingLineNumber]="s.start_line"
                      [customStyle]="{ margin: '0', fontSize: '11.5px', borderTop: '1px solid var(--border-subtle)', borderRadius: '0', maxHeight: '260px' }"
                    >{{ s.content }}</app-highlighted-code>
                  }
                  @if (gitLabSourceUrl(s.file_path, s.start_line, s.end_line); as url) {
                    <a [href]="url" target="_blank" rel="noreferrer" class="source-link">abrir en GitLab ↗</a>
                  }
                </div>
              }
            </div>
          }
        </div>
      }

      @if (loading() && !messages()[messages().length - 1]?.streaming) {
        <div class="message thinking">pensando…</div>
      }
    </div>

    <form class="input-row" (submit)="onAsk($event)">
      <input
        #inputEl
        [value]="question()"
        (input)="question.set($any($event.target).value)"
        placeholder="¿cómo se autentican los usuarios?"
        class="input"
        [disabled]="loading()"
      />
      @if (loading()) {
        <button type="button" class="stop-btn" (click)="onStop()">■ parar</button>
      } @else {
        <button type="submit" class="send-btn" [disabled]="!question().trim()">enviar</button>
      }
    </form>
  </div>
}
