// frontend/src/components/WikiPageContent.jsx
import { useCallback, useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Check, History, Pencil, RotateCcw, Upload, X } from "lucide-react";
import { MermaidDiagram } from "./MermaidDiagram";
import { RevisionPanel, PushToGitLabDialog } from "./RevisionPanel";
import { gitLabSourceUrl } from "../utils/gitlab";
import { HighlightedCode } from "./HighlightedCode";

// ---------------------------------------------------------------------------
// Toast
// ---------------------------------------------------------------------------

function Toast({ message, onHide }) {
  useEffect(() => {
    const t = setTimeout(onHide, 2400);
    return () => clearTimeout(t);
  }, [onHide]);

  return (
    <div style={styles.toast}>
      <Check size={13} />
      {message}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Code block with copy button
// ---------------------------------------------------------------------------

function CodeBlock({ lang, children }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(children).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    });
  }, [children]);

  return (
    <div style={styles.codeWrapper}>
      <button
        style={{ ...styles.copyBtn, color: copied ? "var(--accent-sage)" : "var(--text-tertiary)" }}
        onClick={handleCopy}
        title="Copiar código"
      >
        {copied ? <Check size={11} /> : "⎘"}
      </button>
      <HighlightedCode
        language={lang}
        customStyle={{
          borderRadius: 8,
          fontSize: 12.5,
          border: "1px solid var(--border-subtle)",
          margin: "16px 0",
        }}
      >
        {children.replace(/\n$/, "")}
      </HighlightedCode>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export function WikiPageContent({ page, repositoryId, repository, onUpdatePage, onRegenerate }) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedContent, setEditedContent] = useState("");
  const [isSaving, setIsSaving] = useState(false);
  const [saveError, setSaveError] = useState("");
  const [showRevisions, setShowRevisions] = useState(false);
  const [showPushDialog, setShowPushDialog] = useState(false);
  const [toast, setToast] = useState(null);

  const hideToast = useCallback(() => setToast(null), []);

  // Reset editing state when navigating to a different page (during-render pattern,
  // avoids calling setState inside useEffect which causes an extra render cycle).
  const [prevSlug, setPrevSlug] = useState(page?.slug);
  if (prevSlug !== page?.slug) {
    setPrevSlug(page?.slug);
    setIsEditing(false);
    setEditedContent("");
    setSaveError("");
    setShowRevisions(false);
    setToast(null);
  }

  if (!page) return null;

  const handleEditStart = () => {
    setEditedContent(page.content_markdown);
    setSaveError("");
    setIsEditing(true);
  };

  const handleSave = async () => {
    setIsSaving(true);
    setSaveError("");
    try {
      await onUpdatePage(page.slug, editedContent);
      setIsEditing(false);
      setToast("Guardado correctamente");
    } catch (err) {
      setSaveError(err.message || "No se pudo guardar la página.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleCancel = () => {
    setIsEditing(false);
    setEditedContent("");
    setSaveError("");
  };

  const handleRestored = (restoredPage) => {
    onUpdatePage?.(restoredPage.slug, restoredPage.content_markdown, restoredPage);
    setToast("Revisión restaurada");
  };

  return (
    <article style={styles.article} className="wiki-article">
      {toast && <Toast message={toast} onHide={hideToast} />}

      <div style={styles.pageHeader} className="wiki-page-header">
        <h1 style={styles.h1}>{page.title}</h1>
        <div style={styles.pageActions}>
          {!isEditing && onUpdatePage && (
            <>
              <button onClick={() => setShowPushDialog(true)} style={styles.actionButton} title="Publicar en GitLab Wiki">
                <Upload size={14} />
                GitLab Wiki
              </button>
              <button onClick={() => setShowRevisions(true)} style={styles.actionButton} title="Ver historial de revisiones">
                <History size={14} />
                Historial
              </button>
              <button onClick={handleEditStart} style={styles.editButton} title="Editar página (E)">
                <Pencil size={14} />
                Editar
              </button>
              {page.is_ai_generated && onRegenerate && (
                <button onClick={() => onRegenerate(page.slug)} style={styles.actionButton} title="Regenerar solo esta página">
                  <RotateCcw size={14} /> Regenerar
                </button>
              )}
            </>
          )}
          {isEditing && (
            <div style={styles.editActions}>
              {saveError && <span style={styles.saveError}>{saveError}</span>}
              <button onClick={handleSave} disabled={isSaving} style={styles.saveButton}>
                <Check size={14} />
                {isSaving ? "Guardando…" : "Guardar"}
              </button>
              <button onClick={handleCancel} disabled={isSaving} style={styles.cancelButton}>
                <X size={14} />
                Cancelar
              </button>
            </div>
          )}
        </div>
      </div>

      {isEditing ? (
        <textarea
          value={editedContent}
          onChange={(e) => setEditedContent(e.target.value)}
          style={styles.editor}
          spellCheck={false}
          autoFocus
        />
      ) : (
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={{
            code({ className, children, ...props }) {
              const match = /language-(\w+)/.exec(className || "");
              const lang = match?.[1];
              const codeStr = String(children).replace(/\n$/, "");

              if (lang === "mermaid") {
                return <MermaidDiagram code={codeStr} />;
              }

              if (lang) {
                return <CodeBlock lang={lang}>{codeStr}</CodeBlock>;
              }

              return (
                <code style={styles.inlineCode} {...props}>
                  {children}
                </code>
              );
            },
            h2: (props) => <h2 style={styles.h2} {...props} />,
            h3: (props) => <h3 style={styles.h3} {...props} />,
            p: (props) => <p style={styles.p} {...props} />,
            ul: (props) => <ul style={styles.list} {...props} />,
            ol: (props) => <ol style={styles.list} {...props} />,
            li: (props) => <li style={styles.li} {...props} />,
            a: (props) => <a style={styles.link} {...props} target="_blank" rel="noreferrer" />,
            blockquote: (props) => <blockquote style={styles.blockquote} {...props} />,
            table: (props) => <table style={styles.table} {...props} />,
            th: (props) => <th style={styles.th} {...props} />,
            td: (props) => <td style={styles.td} {...props} />,
          }}
        >
          {page.content_markdown}
        </ReactMarkdown>
      )}

      {page.source_files?.length > 0 && (
        <div style={styles.sourcesBox}>
          <div style={styles.sourcesLabel}>archivos fuente</div>
          <div style={styles.sourcesList}>
            {page.source_files.map((f) => {
              const href = gitLabSourceUrl(repository, f);
              return href ? (
                <a key={f} href={href} target="_blank" rel="noreferrer" style={styles.sourceTag}>{f} ↗</a>
              ) : <span key={f} style={styles.sourceTag}>{f}</span>;
            })}
          </div>
        </div>
      )}

      {showRevisions && repositoryId && (
        <RevisionPanel
          repoId={repositoryId}
          slug={page.slug}
          currentContent={page.content_markdown}
          onRestore={handleRestored}
          onClose={() => setShowRevisions(false)}
        />
      )}

      {showPushDialog && repositoryId && (
        <PushToGitLabDialog repoId={repositoryId} onClose={() => setShowPushDialog(false)} />
      )}
    </article>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = {
  article: {
    maxWidth: 720,
    margin: "0 auto",
    padding: "56px 32px 120px",
    position: "relative",
  },
  toast: {
    position: "fixed",
    bottom: 28,
    right: 28,
    background: "var(--accent-sage-dim)",
    color: "var(--accent-on-sage)",
    borderRadius: 8,
    padding: "10px 18px",
    fontSize: 13,
    fontFamily: "var(--font-mono)",
    display: "flex",
    alignItems: "center",
    gap: 8,
    zIndex: 300,
    boxShadow: "0 4px 20px rgba(0,0,0,0.4)",
    animation: "fadeIn 0.15s ease",
  },
  pageHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 28,
  },
  pageActions: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
    marginTop: 6,
  },
  actionButton: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 10px",
    fontSize: 12,
    fontFamily: "var(--font-mono)",
    color: "var(--text-tertiary)",
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    cursor: "pointer",
  },
  editButton: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 12px",
    fontSize: 12,
    fontFamily: "var(--font-mono)",
    color: "var(--text-tertiary)",
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    cursor: "pointer",
  },
  editActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  saveButton: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 12px",
    fontSize: 12,
    fontFamily: "var(--font-mono)",
    color: "var(--accent-on-rust)",
    background: "var(--accent-rust)",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
  },
  cancelButton: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 12px",
    fontSize: 12,
    fontFamily: "var(--font-mono)",
    color: "var(--text-secondary)",
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    cursor: "pointer",
  },
  saveError: {
    fontSize: 11,
    color: "var(--accent-red)",
    fontFamily: "var(--font-mono)",
  },
  editor: {
    width: "100%",
    minHeight: 480,
    padding: "16px",
    fontSize: 13.5,
    fontFamily: "var(--font-mono)",
    color: "var(--text-primary)",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 8,
    resize: "vertical",
    outline: "none",
    lineHeight: 1.6,
    boxSizing: "border-box",
    marginBottom: 8,
  },
  h1: {
    fontFamily: "var(--font-serif)",
    fontSize: 36,
    fontWeight: 700,
    color: "var(--text-primary)",
    margin: 0,
    letterSpacing: "-0.01em",
    lineHeight: 1.2,
  },
  h2: {
    fontFamily: "var(--font-serif)",
    fontSize: 23,
    fontWeight: 600,
    color: "var(--text-primary)",
    margin: "40px 0 14px",
    borderTop: "1px solid var(--border-subtle)",
    paddingTop: 28,
  },
  h3: {
    fontFamily: "var(--font-serif)",
    fontSize: 18,
    fontWeight: 600,
    color: "var(--text-primary)",
    margin: "28px 0 10px",
  },
  p: {
    fontFamily: "var(--font-serif)",
    fontSize: 16.5,
    lineHeight: 1.75,
    color: "var(--text-secondary)",
    margin: "0 0 16px",
  },
  list: {
    fontFamily: "var(--font-serif)",
    fontSize: 16.5,
    lineHeight: 1.75,
    color: "var(--text-secondary)",
    margin: "0 0 16px",
    paddingLeft: 24,
  },
  li: {
    marginBottom: 6,
  },
  link: {
    color: "var(--accent-rust)",
    textDecoration: "underline",
    textDecorationColor: "var(--accent-rust-dim)",
  },
  blockquote: {
    borderLeft: "3px solid var(--accent-rust)",
    margin: "20px 0",
    padding: "4px 0 4px 18px",
    color: "var(--text-tertiary)",
    fontStyle: "italic",
    fontFamily: "var(--font-serif)",
  },
  inlineCode: {
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 4,
    padding: "2px 6px",
    fontSize: "0.85em",
    fontFamily: "var(--font-mono)",
    color: "var(--accent-rust)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    margin: "20px 0",
    fontSize: 13.5,
  },
  th: {
    textAlign: "left",
    borderBottom: "1px solid var(--border-strong)",
    padding: "8px 10px",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
  },
  td: {
    borderBottom: "1px solid var(--border-subtle)",
    padding: "8px 10px",
    color: "var(--text-secondary)",
    fontFamily: "var(--font-serif)",
  },
  codeWrapper: {
    position: "relative",
  },
  copyBtn: {
    position: "absolute",
    top: 26,
    right: 8,
    zIndex: 2,
    background: "rgba(32,29,23,0.7)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 4,
    padding: "3px 7px",
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "var(--font-mono)",
    lineHeight: 1,
  },
  sourcesBox: {
    marginTop: 48,
    paddingTop: 20,
    borderTop: "1px solid var(--border-subtle)",
  },
  sourcesLabel: {
    fontSize: 10.5,
    letterSpacing: "0.06em",
    color: "var(--text-tertiary)",
    marginBottom: 10,
  },
  sourcesList: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  sourceTag: {
    fontSize: 11,
    fontFamily: "var(--font-mono)",
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 4,
    padding: "3px 8px",
    color: "var(--text-tertiary)",
  },
};

// frontend/src/app/components/wiki-page-content/wiki-page-content.component.ts
import {
  Component,
  computed,
  signal,
  inject,
  OnDestroy,
} from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { RepoService } from '../../services/repo.service';
import { ApiService } from '../../services/api.service';
import { gitLabSourceUrl } from '../../utils/gitlab-url';
import { HighlightedCodeComponent } from '../highlighted-code/highlighted-code.component';
import { MermaidDiagramComponent } from '../mermaid-diagram/mermaid-diagram.component';
import { RevisionPanelComponent } from '../revision-panel/revision-panel.component';
import { PushToGitLabDialogComponent } from '../revision-panel/push-to-gitlab-dialog.component';

interface MarkdownBlock {
  type: 'mermaid' | 'code' | 'html' | 'empty';
  content: string;
  lang?: string;
}

@Component({
  selector: 'app-wiki-page-content',
  standalone: true,
  imports: [
    HighlightedCodeComponent,
    MermaidDiagramComponent,
    RevisionPanelComponent,
    PushToGitLabDialogComponent,
  ],
  templateUrl: './wiki-page-content.component.html',
  styleUrls: ['./wiki-page-content.component.css'],
})
export class WikiPageContentComponent implements OnDestroy {
  private repoService = inject(RepoService);
  private api = inject(ApiService);
  private sanitizer = inject(DomSanitizer);

  page = this.repoService.activePage;
  repository = this.repoService.repository;

  isEditing = signal(false);
  editedContent = signal('');
  isSaving = signal(false);
  saveError = signal('');
  showRevisions = signal(false);
  showPushDialog = signal(false);
  toast = signal<string | null>(null);

  private toastTimer: ReturnType<typeof setTimeout> | null = null;
  private prevSlug: string | null = null;

  /** Split markdown content into renderable blocks (mermaid, code, HTML). */
  readonly blocks = computed(() => {
    const p = this.page();
    if (!p) return [];
    return this.splitBlocks((p as { content_markdown: string }).content_markdown || '');
  });

  constructor() {
    // Watch for slug changes
    const p = this.page();
    if (p) {
      this.prevSlug = (p as { slug: string }).slug;
    }
  }

  ngOnDestroy(): void {
    if (this.toastTimer) clearTimeout(this.toastTimer);
  }

  onEditingChange(): void {
    const p = this.page();
    if (!p) return;
    const slug = (p as { slug: string }).slug;
    if (slug !== this.prevSlug) {
      this.prevSlug = slug;
      this.isEditing.set(false);
      this.editedContent.set('');
      this.saveError.set('');
      this.showRevisions.set(false);
      this.toast.set(null);
    }
  }

  /** Split markdown into mermaid blocks, code blocks, and HTML-rendered rest. */
  private splitBlocks(markdown: string): MarkdownBlock[] {
    const blocks: MarkdownBlock[] = [];
    const lines = markdown.split('\n');
    let i = 0;

    while (i < lines.length) {
      // Mermaid block
      if (lines[i].trim() === '```mermaid') {
        i++;
        const contentLines: string[] = [];
        while (i < lines.length && lines[i].trim() !== '```') {
          contentLines.push(lines[i]);
          i++;
        }
        i++;
        blocks.push({ type: 'mermaid', content: contentLines.join('\n') });
        continue;
      }

      // Code block
      const codeMatch = lines[i].match(/^```(\w*)/);
      if (codeMatch) {
        const lang = codeMatch[1] || 'text';
        i++;
        const contentLines: string[] = [];
        while (i < lines.length && lines[i].trim() !== '```') {
          contentLines.push(lines[i]);
          i++;
        }
        i++;
        blocks.push({ type: 'code', content: contentLines.join('\n'), lang });
        continue;
      }

      // Regular markdown lines
      const htmlLines: string[] = [];
      while (i < lines.length && !lines[i].match(/^```/)) {
        htmlLines.push(lines[i]);
        i++;
      }

      if (htmlLines.length > 0) {
        const text = htmlLines.join('\n').trim();
        if (text) {
          blocks.push({ type: 'html', content: text });
        }
      } else {
        blocks.push({ type: 'empty', content: '' });
      }
    }

    return blocks;
  }

  /** Convert markdown text to safe HTML */
  markdownToHtml(text: string): SafeHtml {
    let html = text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/`([^`]+)`/g, '<code class="inline-code">$1</code>')
      .replace(
        /\[([^\]]+)\]\(([^)]+)\)/g,
        '<a href="$2" target="_blank" rel="noreferrer">$1</a>',
      )
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/^\d+\. (.+)$/gm, '<li>$1</li>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br>');

    html = '<p>' + html + '</p>';
    html = html.replace(/<p>\s*<\/p>/g, '');
    return this.sanitizer.bypassSecurityTrustHtml(html);
  }

  handleEditStart(): void {
    const p = this.page() as { content_markdown: string } | null;
    if (!p) return;
    this.editedContent.set(p.content_markdown);
    this.saveError.set('');
    this.isEditing.set(true);
  }

  async handleSave(): Promise<void> {
    const repo = this.repository() as { id: number } | null;
    const p = this.page() as { slug: string } | null;
    if (!repo || !p) return;

    this.isSaving.set(true);
    this.saveError.set('');
    try {
      const result = await this.api
        .updateWikiPage(repo.id, p.slug, this.editedContent())
        .toPromise();
      this.repoService.activePage.set(result as any);
      this.isEditing.set(false);
      this.showToast('Guardado correctamente');
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'No se pudo guardar la página.';
      this.saveError.set(msg);
    } finally {
      this.isSaving.set(false);
    }
  }

  handleCancel(): void {
    this.isEditing.set(false);
    this.editedContent.set('');
    this.saveError.set('');
  }

  handleRestored(restoredPage: unknown): void {
    this.repoService.activePage.set(restoredPage as any);
    this.showToast('Revisión restaurada');
  }

  private showToast(message: string): void {
    this.toast.set(message);
    if (this.toastTimer) clearTimeout(this.toastTimer);
    this.toastTimer = setTimeout(() => this.toast.set(null), 2400);
  }

  async copyCode(code: string): Promise<void> {
    try {
      await navigator.clipboard.writeText(code);
    } catch { /* ignore */ }
  }

  gitLabSourceUrl(filePath: string): string | null {
    const repo = this.repository() as Record<string, unknown> | null;
    if (!repo) return null;
    return gitLabSourceUrl(repo as any, filePath);
  }
}

@if (page(); as p) {
  <article class="wiki-article">
    @if (toast(); as msg) {
      <div class="toast">{{ msg }}</div>
    }

    <div class="page-header">
      <h1 class="h1">{{ (p as any).title }}</h1>
      <div class="page-actions">
        @if (!isEditing()) {
          <button class="action-button" (click)="showPushDialog.set(true)" title="Publicar en GitLab Wiki">
            ↑ GitLab Wiki
          </button>
          <button class="action-button" (click)="showRevisions.set(true)" title="Ver historial de revisiones">
            ◷ Historial
          </button>
          <button class="action-button edit-btn" (click)="handleEditStart()" title="Editar página (E)">
            ✎ Editar
          </button>
          @if ((p as any).is_ai_generated) {
            <button class="action-button" (click)="repoService.handleRegeneratePage((p as any).slug)" title="Regenerar solo esta página">
              ↻ Regenerar
            </button>
          }
        } @else {
          <div class="edit-actions">
            @if (saveError()) {
              <span class="save-error">{{ saveError() }}</span>
            }
            <button class="save-btn" (click)="handleSave()" [disabled]="isSaving()">
              ✓ {{ isSaving() ? 'Guardando…' : 'Guardar' }}
            </button>
            <button class="cancel-btn" (click)="handleCancel()" [disabled]="isSaving()">
              ✕ Cancelar
            </button>
          </div>
        }
      </div>
    </div>

    @if (isEditing()) {
      <textarea
        class="editor"
        [value]="editedContent()"
        (input)="editedContent.set($any($event.target).value)"
        spellcheck="false"
      ></textarea>
    } @else {
      @for (block of blocks(); track $index) {
        @if (block.type === 'mermaid') {
          <app-mermaid-diagram [code]="block.content" />
        } @else if (block.type === 'code') {
          <div class="code-wrapper">
            <button class="copy-btn" (click)="copyCode(block.content)" title="Copiar código">⎘</button>
            <app-highlighted-code
              [language]="block.lang || 'text'"
              [customStyle]="{ borderRadius: '8px', fontSize: '12.5px', border: '1px solid var(--border-subtle)', margin: '16px 0' }"
            >{{ block.content }}</app-highlighted-code>
          </div>
        } @else if (block.type === 'html') {
          <div class="markdown-body" [innerHTML]="markdownToHtml(block.content)"></div>
        }
      }
    }

    @if ((p as any).source_files?.length > 0) {
      <div class="sources-box">
        <div class="sources-label">archivos fuente</div>
        <div class="sources-list">
          @for (f of (p as any).source_files; track f) {
            @if (gitLabSourceUrl(f); as href) {
              <a [href]="href" target="_blank" rel="noreferrer" class="source-tag">{{ f }} ↗</a>
            } @else {
              <span class="source-tag">{{ f }}</span>
            }
          }
        </div>
      </div>
    }

    @if (showRevisions()) {
      <app-revision-panel
        [repoId]="(repository() as any)?.id"
        [slug]="(p as any).slug"
        [currentContent]="(p as any).content_markdown"
        (restore)="handleRestored($event)"
        (close)="showRevisions.set(false)"
      />
    }

    @if (showPushDialog()) {
      <app-push-to-gitlab-dialog
        [repoId]="(repository() as any)?.id"
        (close)="showPushDialog.set(false)"
      />
    }
  </article>
}
